name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分鐘自動執行

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://ai-news-api-9r4w.onrender.com/smart_news > /dev/null
